### ISSUE TITLE
Alternative Approach

### ISSUE THREAD

**Issue by kartiksharmakk** [DawinderGill/BottomTabNavigation-JetpackCompose#1]
Hi , When i was adapting this code for my app  i faced an issue with NavigationScreens.kt  , basically it was a navigation related exception error .

I solved it by using my equivalent of NavigationScreens()  inside of MainActivity  instead of MainScreen() . (i kept the bottom bar within the NavigationScreens() which was earlier in MainScreen()).

```kt
@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
@Composable
fun NavigationScreens() {
    val navController = rememberNavController()
    Scaffold(bottomBar = {
        BottomAppBar { BottomNavigationBar(navController = navController) }
    }) {
    }
 NavHost(navController = navController, startDestination = NavItem.Home.path) {

           composable(NavItem.Home.path){
               HomeScreen(navController = navController)
           }
}
```

 I think it would be a better approach  as we are directly utilizing our Navigation at first instance which itself would start the homeScreen as intended . MainScreen could be removed and its components could be kept directly inside the NavigationScreens()

https://github.com/DawinderGill/BottomTabNavigation-JetpackCompose/blob/b2dc2830d487d00242918abe8acae10a1b0cfc4e/app/src/main/java/com/dawinder/btnjc/ui/activities/MainActivity.kt#L41

**Comment by DawinderGill** [comment]
Hi [kartiksharmakk](https://github.com/kartiksharmakk), Your approach is better. I have just created a basic demo application and you are free to make modifications to it according to your needs. I appreciate that you bring this up.

**Comment by kartiksharmakk** [comment]
Thank you for making this great piece of code . Very useful ❤️
